import type {NextPage} from 'next';
import Head from 'next/head';
import Sitebar from '../components/Sitebar';

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>WhapsApp</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Sitebar />
        </div>
    );
};

export default Home;
