import {Button} from '@mui/material';
import Head from 'next/head';
import Image from 'next/image';
import styled from 'styled-components';
import WhapsAppLogo from '../images/whatsapplogo.png';
import {useSignInWithGoogle} from 'react-firebase-hooks/auth'
import { auth } from '../config/firebase';

const StyledContainer = styled.div`
    display: grid;
    place-items: center;
    height: 100vh;
    background-color: whitesmoke;
`;

const StyledLoginContainer = styled.div`
    display: flex;
    align-items: center;
    flex-direction: column;
    padding: 50px;
    border-radius: 5px;
    box-shadow: 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1);
    background-color: white;
`;
const StyledImageWrapper = styled.div`
    margin-bottom: 50px;
`;

const Login = () => {
    const [signInWithGoogle, _user, _loading, error] = useSignInWithGoogle(auth);

    const handleSignIn = () => {
        signInWithGoogle();
    }

    return (
        <StyledContainer>
            <Head>
                <title>Đăng nhập</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <StyledLoginContainer>
                <StyledImageWrapper>
                    <Image src={WhapsAppLogo} height='200px' width='200px' alt='logo' />
                </StyledImageWrapper>
                <Button variant='outlined' color='primary' size='large' onClick={handleSignIn}>
                    Đăng nhập bằng google
                </Button>
            </StyledLoginContainer>
        </StyledContainer>
    );
};

export default Login;
